### PR TITLE
Implement cluster

### PR DESCRIPTION
**Pull request by ntk148v**
Closes: #27

### CODE REVIEW

**Comment by ntk148v** [comment]
@hieulq review hộ em nhé.

**Comment by hieulq** [comment]
> @hieulq review hộ em nhé.

@ntk148v 574 changes, 80 commits, you f*ck me up

**Comment by vtdat** [comment]
noice ;)

**Comment by ntk148v** [comment]
> > @hieulq review hộ em nhé.
> 
> @ntk148v 574 changes, 80 commits, you f*ck me up

fine la.

**Pull request merged**
